apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
     version: "4"
  template:
    metadata:
      labels:
        version: "4"
    spec:
      containers:
      - name: myflaskapp
        image: pvass24/myflaskapp:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-values
              key: USERNAME
        - name: BG_COLOR
          valueFrom:
            configMapKeyRef:
              name: env-values
              key: BG_COLOR
        - name: FONT_COLOR
          valueFrom:
            configMapKeyRef:
              name: env-values
              key: FONT_COLOR
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 100m  # 0.1 CPU cores
          limits:
            cpu: 200m  # 0.2 CPU cores
