apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-web
  template:
    metadata:
      labels:
        app: ecom-web
    spec:
      containers:
      - name: ecom-web
        image: pvass24/ecom-web:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mysql-service # Ensure this matches your DB service name
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "ecomdb"
        - name: DB_USER
          value: "ecomuser"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password

