
name: Deploy Resume Website to S3

on:
  # Trigger this workflow on pushes to the main branch
  push:
    branches:
      - main

permissions:
  id-token: write # Allow GitHub Actions to request an OIDC token
  contents: read  # Allow access to the repository contents

jobs:
  deploy_to_s3:
    name: Deploy to S3
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ACCOUNT_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: List S3 Buckets
      - name: List S3 Buckets
        run: |
          aws s3 ls
